package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/google/gopacket"
	"github.com/google/gopacket/layers"
	"github.com/google/gopacket/pcap"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	packetsSeen = promauto.NewCounter(prometheus.CounterOpts{
		Name: "nids_packets_seen_total",
		Help: "Total packets processed by the NIDS capture service",
	})
	flowsActive = promauto.NewGauge(prometheus.GaugeOpts{
		Name: "nids_active_flows",
		Help: "Number of active TCP/UDP flows currently tracked",
	})
	flowBytes = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "nids_flow_bytes_total",
		Help: "Bytes processed per protocol",
	}, []string{"protocol"})
	packetLatency = promauto.NewHistogram(prometheus.HistogramOpts{
		Name: "nids_packet_processing_seconds",
		Help: "Packet processing latency in seconds",
		Buckets: prometheus.DefBuckets,
	})
	alertsGenerated = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "nids_alerts_generated_total",
		Help: "Total alerts generated by type",
	}, []string{"alert_type", "severity"})
	anomalyScore = promauto.NewHistogram(prometheus.HistogramOpts{
		Name: "nids_anomaly_score",
		Help: "Distribution of anomaly scores",
		Buckets: []float64{0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9},
	})
)

type FlowKey struct {
	SrcIP   string
	DstIP   string
	SrcPort uint16
	DstPort uint16
	Proto   string
}

type FlowState struct {
	Key             FlowKey
	Start           time.Time
	LastSeen        time.Time
	PacketCount     int
	ByteCount       int
	ForwardPayload  int
	BackwardPayload int
	SynCount        int
	AckCount        int
	RstCount        int
	FinCount        int
	PayloadEntropy  float64
	mu              sync.Mutex
}

type Alert struct {
	ID             string    `json:"id"`
	Type           string    `json:"type"`
	Classification string    `json:"classification"`
	Severity       string    `json:"severity"`
	Score          float64   `json:"score"`
	Message        string    `json:"message"`
	FlowID         string    `json:"flow_id"`
	SrcIP          string    `json:"src_ip"`
	DstIP          string    `json:"dst_ip"`
	DstPort        uint16    `json:"dst_port"`
	CreatedAt      time.Time `json:"created_at"`
}

func main() {
	iface := "eth0"
	if len(os.Args) > 1 {
		for i, arg := range os.Args {
			if arg == "--iface" && i+1 < len(os.Args) {
				iface = os.Args[i+1]
			}
		}
	}

	if err := runCapture(iface); err != nil {
		log.Fatalf("capture service failed: %v", err)
	}
}

func runCapture(iface string) error {
	devices, err := pcap.FindAllDevs()
	if err != nil {
		return fmt.Errorf("find devices: %w", err)
	}

	if len(devices) == 0 {
		return fmt.Errorf("no network devices found")
	}

	fmt.Printf("Available interfaces:\n")
	for _, dev := range devices {
		fmt.Printf(" - %s\n", dev.Name)
	}

	handle, err := pcap.OpenLive(iface, 65535, true, pcap.BlockForever)
	if err != nil {
		return fmt.Errorf("open %s: %w", iface, err)
	}
	defer handle.Close()

	packetSource := gopacket.NewPacketSource(handle, handle.LinkType())
	packetChan := packetSource.Packets()

	start := time.Now()
	flows := make(map[string]*FlowState)
	alertChan := make(chan Alert, 100)

	// Alert handler goroutine
	go handleAlerts(alertChan)

	for {
		select {
		case packet, ok := <-packetChan:
			if !ok {
				return fmt.Errorf("capture channel closed")
			}
			if packet == nil {
				continue
			}

			startTs := time.Now()
			flow, okFlow := processPacket(packet)
			if okFlow {
				key := flowKeyToString(flow.Key)
				state, exists := flows[key]
				if !exists {
					state = &FlowState{Key: flow.Key, Start: time.Now(), LastSeen: time.Now()}
					flows[key] = state
				}
				state.mu.Lock()
				state.PacketCount++
				state.ByteCount += int(packet.Metadata().CaptureLength)
				state.LastSeen = time.Now()
				state.ForwardPayload += flow.ForwardPayload
				state.BackwardPayload += flow.BackwardPayload
				state.SynCount += flow.SynCount
				state.AckCount += flow.AckCount
				state.RstCount += flow.RstCount
				state.FinCount += flow.FinCount
				state.mu.Unlock()

				// Check for anomalies and generate alerts
				if alert := checkAnomaly(state); alert != nil {
					alertChan <- *alert
				}
			}

			packetsSeen.Inc()
			packetLatency.Observe(time.Since(startTs).Seconds())
			flowsActive.Set(float64(len(flows)))

			if time.Since(start) > 30*time.Second {
				for key, v := range flows {
					if time.Since(v.LastSeen) > 2*time.Minute {
						delete(flows, key)
					}
				}
				start = time.Now()
			}
		}
	}
}

func processPacket(packet gopacket.Packet) (*FlowState, bool) {
	ipLayer := packet.Layer(layers.LayerTypeIPv4)
	if ipLayer == nil {
		return nil, false
	}
	ip, ok := ipLayer.(*layers.IPv4)
	if !ok {
		return nil, false
	}

	var proto string
	var srcPort, dstPort uint16
	payloadLen := len(packet.Data())

	tcpLayer := packet.Layer(layers.LayerTypeTCP)
	if tcpLayer != nil {
		tcp, ok := tcpLayer.(*layers.TCP)
		if ok {
			proto = "tcp"
			srcPort = uint16(tcp.SrcPort)
			dstPort = uint16(tcp.DstPort)
			payloadLen = len(tcp.Payload)
		}
	}

	udpLayer := packet.Layer(layers.LayerTypeUDP)
	if udpLayer != nil {
		udp, ok := udpLayer.(*layers.UDP)
		if ok {
			proto = "udp"
			srcPort = uint16(udp.SrcPort)
			dstPort = uint16(udp.DstPort)
			payloadLen = len(udp.Payload)
		}
	}

	if proto == "" {
		return nil, false
	}

	flow := &FlowState{
		Key: FlowKey{
			SrcIP:   ip.SrcIP.String(),
			DstIP:   ip.DstIP.String(),
			SrcPort: srcPort,
			DstPort: dstPort,
			Proto:   proto,
		},
		Start:    time.Now(),
		LastSeen: time.Now(),
	}

	flow.ForwardPayload = payloadLen
	flow.ByteCount = payloadLen
	flow.PacketCount = 1
	flow.PayloadEntropy = calculateEntropy(packet.Data())

	if tcpLayer != nil {
		tcp, ok := tcpLayer.(*layers.TCP)
		if ok {
			if tcp.SYN && !tcp.ACK {
				flow.SynCount = 1
			}
			if tcp.ACK {
				flow.AckCount = 1
			}
			if tcp.RST {
				flow.RstCount = 1
			}
			if tcp.FIN {
				flow.FinCount = 1
			}
		}
	}

	flowBytes.WithLabelValues(proto).Add(float64(payloadLen))
	return flow, true
}

func checkAnomaly(flow *FlowState) *Alert {
	flow.mu.Lock()
	defer flow.mu.Unlock()

	// Calculate anomaly score based on flow characteristics
	score := 0.0
	alertType := ""
	classification := ""
	severity := "low"
	message := ""

	// Port scan detection
	if flow.SynCount > 5 && flow.AckCount < flow.SynCount/2 {
		score += 0.6
		alertType = "port_scan"
		classification = "reconnaissance"
		message = "Potential port scan detected"
	}

	// High packet rate (potential flood)
	if flow.PacketCount > 100 && time.Since(flow.Start) < 5*time.Second {
		score += 0.4
		alertType = "high_packet_rate"
		classification = "anomalous_behavior"
		message = "Abnormally high packet rate detected"
	}

	// Large data transfer
	if flow.ByteCount > 10000000 {
		score += 0.3
		alertType = "data_exfiltration"
		classification = "data_theft"
		message = "Large data transfer detected"
	}

	// RST flood
	if flow.RstCount > 10 {
		score += 0.5
		alertType = "rst_flood"
		classification = "denial_of_service"
		message = "Abnormal RST flag frequency"
	}

	// High entropy payload (potential encryption/shellcode)
	if flow.PayloadEntropy > 7.5 {
		score += 0.4
		alertType = "high_entropy_payload"
		classification = "potential_malware"
		message = "High entropy payload detected"
	}

	// Generate alert if score exceeds threshold
	if score > 0.5 {
		if score > 0.8 {
			severity = "critical"
		} else if score > 0.65 {
			severity = "high"
		} else if score > 0.5 {
			severity = "medium"
		}

		alertsGenerated.WithLabelValues(alertType, severity).Inc()
		anomalyScore.Observe(score)

		return &Alert{
			ID:             fmt.Sprintf("alert-%d", time.Now().UnixNano()),
			Type:           alertType,
			Classification: classification,
			Severity:       severity,
			Score:          score * 100,
			Message:        message,
			FlowID:         flowKeyToString(flow.Key),
			SrcIP:          flow.Key.SrcIP,
			DstIP:          flow.Key.DstIP,
			DstPort:        flow.Key.DstPort,
			CreatedAt:      time.Now().UTC(),
		}
	}

	return nil
}

func calculateEntropy(data []byte) float64 {
	if len(data) == 0 {
		return 0.0
	}

	freq := make(map[byte]int)
	for _, b := range data {
		freq[b]++
	}

	entropy := 0.0
	for _, count := range freq {
		p := float64(count) / float64(len(data))
		entropy -= p * (log2(p))
	}

	return entropy
}

func log2(x float64) float64 {
	return math.Log(x) / math.Log(2.0)
}

func handleAlerts(alertChan chan Alert) {
	for alert := range alertChan {
		data, _ := json.Marshal(alert)
		fmt.Printf("[ALERT] %s\n", string(data))
	}
}

func flowKeyToString(key FlowKey) string {
	return strings.Join([]string{
		key.SrcIP,
		key.DstIP,
		strconv.Itoa(int(key.SrcPort)),
		strconv.Itoa(int(key.DstPort)),
		key.Proto,
	}, "|")
}